### ISSUE TITLE
实时人脸检测

### ISSUE THREAD

**Issue by jp1017** [lchad/AndroidFaceDetection#1]
https://github.com/XXApple/AndroidLibs/commit/93955c574621f25ec985230deb513f897c3819de#diff-30358778c68a66f86dc0671ff23f9dfeR25

**Comment by MhuiHugh** [comment]
openCV 编译不通过了，Camera Api小米手机上启动闪退，分析对比后推荐 https://github.com/xiaoyaoyou1212/ViseFace
